// today-blog-ui/today-blog-ui-mobile/src/components/article-list/index.vue
<template>
  <div>
    <van-skeleton v-if="loading" title :row="3" class="skeleton"/>
    <van-empty v-else-if="showEmpty" description="暂无文章"/>
    <div v-else class="article-list">
      <div v-for="article in articles" class="article">
        <h2>
          <router-link :to="`/articles/${article.id}`">{{ article.title }}</router-link>
        </h2>
        <div class="tags">
          <router-link :key="idx" v-for="(label ,idx) in article.labels"
                       :class="getRandLabel()" :to="`/tags/${ label.name }`" :title="label.name">{{ label.name }}
          </router-link>
        </div>
        <div class="summary" @click="showDetail(article.id)">
          {{ article.summary }}
        </div>
        <div class="img" v-if="article.image">
          <van-image lazy-load :src="article.image" @click="imagePreview(article.image)">
            <template v-slot:loading>
              <van-loading type="spinner" size="30"/>
            </template>
            <template v-slot:error>加载失败</template>
          </van-image>
        </div>
        <div class="info">
          {{ new Date(article.id).toLocaleString() }} | <span class="read-num"> 阅读数 <span class="num">{{ article.pv }}</span></span>
        </div>
        <hr/>
      </div>
    </div>
  </div>
</template>


<script>
import Vue from 'vue';
import { Image as VanImage, ImagePreview, Tag } from 'vant';

import { getRandLabel, isEmpty, isNotEmpty } from 'src/utils';

Vue.use(Tag);
Vue.use(ImagePreview);
Vue.use(VanImage);

export default {
  name: "article-list",
  components: {},
  props: {
    loading: {
      type: Boolean,
    },
    articles: {
      type: Array,
    }
  },
  data() {
    return {}
  },
  computed: {
    showEmpty() {
      return !this.loading && isEmpty(this.articles);
    },
  },
  mounted() {
  },
  methods: {
    isEmpty,
    isNotEmpty,
    getRandLabel,
    imagePreview(image) {
      ImagePreview([image])
    },
    showDetail(id) {
      this.$router.push(`/articles/${ id }`)
    },
  }
}
</script>

<style lang="less">
.skeleton {
  padding-bottom: 10px;
}

.article-list {
  background: #fff;

  .article {
    padding: 10px;
  }

  .num {
    color: #3399ea;
  }

  .read-num {
    color: #999;
  }

  .info {
    text-align: right;
  }

  .tags {
    margin-bottom: 10px;
  }

  h2 {
    margin-bottom: 10px;
  }

  .img {
    margin: 10px 0 10px 0;
  }

  .summary {
    font-size: 15px;
    color: #6b6b6b;
    word-wrap: break-word !important;
    white-space: normal;
  }

  hr {
    border: none;
    border-top: 1px dashed #c8dde4;
    margin-bottom: 0;
  }
}


</style>

// today-blog-ui/today-blog-ui-desktop/src/components/ArticleList.jsx
import { Empty, Result, Skeleton } from 'antd';
import React from 'react';
import { Link, } from "react-router-dom";
import { withRouter } from "react-router";

import { arrayNotEquals, getRandLabel, isNotEmpty } from '../utils';
import { Image } from './';
import { connect } from "react-redux";
import { userSessionMapStateToProps } from "../redux/action-types";
import { updateUserSession } from "../redux/actions";
import HttpError from "./http/HttpError";

class ArticleList extends React.Component {

  shouldComponentUpdate(nextProps, nextState) {
    return arrayNotEquals(this.props.articles, nextProps.articles)
  }

  render() {
    let { error, errorTitle, title } = this.props;
    if (error) {

      if (!errorTitle) {
        if (title) {
          errorTitle = title + "加载失败"
        }
        else {
          errorTitle = "文章列表加载失败"
        }
      }
      return <HttpError { ...error } title={ errorTitle }/>
    }
    const { articles } = this.props;
    if (!articles) {
      return <Skeleton active/>
    }
    if (articles.length === 0) {
      return <Empty style={ { marginTop: '10px' } } description="暂无文章"/>
    }
    return (<>
      {
        articles.map((article, idx) => {
          return (
              <div key={ article.id } className="article-list">
                <h2><Link to={ `/articles/${ article.id }` } dangerouslySetInnerHTML={ { __html: article.title } }/></h2>
                { isNotEmpty(article.labels) &&
                <span className="tags">{ article.labels.map((label, idx) => {
                  return <Link key={ idx } to={ `/tags/${ label.name }` } className={ getRandLabel() } title={ label.name }>{ label.name }</Link>
                }) }
                </span>
                }
                <span className="summary" dangerouslySetInnerHTML={ { __html: article.summary } }
                      onClick={ () => this.props.history.push(`/articles/${ article.id }`) }/>
                { isNotEmpty(article.image) &&
                <span className="img">
                  <Image alt={ article.summary } src={ article.image } original={ false }/>
                </span>
                }
                <span className="info">
                  { new Date(article.id).toLocaleString() } | <span className="read-num"> 阅读数 <span className="num">{ article.pv }</span></span>
                </span>
                <hr/>
              </div>
          )
        })
      }
    </>)
  }
}

export default connect(
    userSessionMapStateToProps, { updateUserSession }
)(withRouter(ArticleList))
